modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"

[[mods]]
modId="worldrise"
version="1.0.0"
displayName="Worldrise"
authors="Your Team"
description='''
Worldrise expands Minecraft's world height and depth, rescales ores and
structures, adds custom carvers, and provides compatibility with
popular biome/ore mods.
'''

[[dependencies.worldrise]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"
