modLoader = "javafml"
loaderVersion = "[10,)"
license = "MIT"

[[mods]]
modId = "the_expanse"
version = "${version}"
displayName = "The Expanse"
authors = "CyberDay1"
description = '''
Expands Minecraft's world height, carvers, and ore distributions.
'''

# Dependencies
[[dependencies.the_expanse]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_expanse]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcVersion}]"
ordering = "NONE"
side = "BOTH"
