modLoader="javafml"
loaderVersion="[2,)"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
displayURL="${homepage_url}"
issueTrackerURL="${issues_url}"

[[mixins]]  # Remove this block if you do not use mixins
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${mc_version}]"
ordering="NONE"
side="BOTH"
