[worldrise]
oreScaling = true
carverEnabled = true
megaRavines = true
sinkholes = true
blueHoles = true
strongholdScaling = true
ancientCityScaling = true
mineshaftScaling = true
fortressScaling = true
bastionScaling = true
monumentScaling = true
endCityScaling = true
netherScaling = true
endScaling = true
oreDensityMultiplier = 1.0
carverChanceMultiplier = 1.0
tectonicEnabled = true
lithoEnabled = true
