build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: true
    excludes: []

formatting:
  active: true
  android: false
  autoCorrect: false
  Indentation:
    active: true
    indentSize: 4
    continuationIndentSize: 4
  NoWildcardImports:
    active: true

comments:
  CommentOverPrivateFunction:
    active: false

potential-bugs:
  DuplicateCaseInWhenExpression:
    active: true
