modLoader = "neoforge"
loaderVersion = "[${NEOFORGE_VERSION},)"
license = "MIT"

[[mods]]
modId = "the_expanse"
version = "${MOD_VERSION}"
displayName = "The Expanse"
authors = "CyberDay1"
description = '''
Expands Minecraft's world height, carvers, and ore distributions.
'''

[[dependencies.the_expanse]]
modId = "neoforge"
mandatory = true
versionRange = "[${NEOFORGE_VERSION},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_expanse]]
modId = "minecraft"
mandatory = true
versionRange = "[${MC_VERSION},${MC_VERSION_NEXT})"
ordering = "NONE"
side = "BOTH"
