modLoader = "javafml"
loaderVersion = "[1,)" # Accept any 1.x NeoForge loader
license = "MIT"

[[mods]]
modId = "the_expanse"
version = "${version}"
displayName = "The Expanse"
authors = "CyberDay1"
description = '''
Expands Minecraft’s build height and depth across the Overworld, Nether, and End.
'''

# Optional but recommended: logo and credits
# logoFile = "the_expanse.png"
# credits = "Contributors and the modding community"
